# Generated by Django 5.2.10 on 2026-01-28 16:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0010_meetingroom_delete_meeting'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meetingroom',
            name='is_live',
        ),
        migrations.AlterField(
            model_name='meetingroom',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meeting_rooms', to='organizations.organization'),
        ),
        migrations.AlterField(
            model_name='meetingroom',
            name='room_name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
