# Generated by Django 5.2.10 on 2026-01-28 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0011_remove_meetingroom_is_live_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='meetingroom',
            name='is_live',
            field=models.BooleanField(default=False),
        ),
    ]
